var journey=[
    {id:1,
     country:'France',
     city:'Paris'
    },
    {id:2,
     country:'France',
     city:'Marseille'
    },
    {id:3,
     country:'France',
     city:'Montpellier'
    },
    {id:4,
     country:'France',
     city:'Lyon'
    },
    {id:5,
     country:'France',
     city:'Strasbourg'
    },
    /*
    {id:6,
     country:'Netherlands',
     city:'Amsterdam'
    },
    {id:7,
     country:'Ukraine',
     city:'Lviv'
    },
    {id:8,
     country:'Ukraine',
     city:'Kyiv'
    },
    {id:9,
     country:'Germany',
     city:'Berlin'
    },
    {id:10,
     country:'Germany',
     city:'Dresden'
    },
    {id:11,
     country:'Germany',
     city:'Munich'
    },
    {id:12,
     country:'Italy',
     city:'Roma',
    },
    {id:13,
     country:'Italy',
     city:'Milan'
    },
    {id:14,
     country:'Italy',
     city:'Verona'
    },
    {id:15,
     country: 'Italy',
     city:'Florence'
    },
    {id:16,
     country:'Italy',
     city:'Padova'
    },
    {id:17,
     country:'Italy',
     city:'Desenzano'
    },
    {id:18,
     country:'Italy',
     city:'Sermione'
    },
    {id:19,
     country:'Czech',
     city:'Prague'
    },
    {id:20,
     country:'Poland',
     city:'Krakow'
    },
    {id:21,
     country:'Poland',
     city:'Warszawa'
    },
    {id:22,
     country:'Poland',
     city:'Wroclaw'
    },
    {id:23,
     country:'Poland',
     city:'Opole'
    },
    {id:24,
     country:'Spain',
     city:'Barcelona'
    },
    */
];
